version: "3"
services: 

  # NodeJS Server
  nodejs:
    # container_name: docker-node-mongo
    build: .
    restart: always
    environment:
      - PORT=3000
    ports: 
      - 3000:3000
    links:
      - mongo
    networks:
      - snakenet 

# Mongo Container
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017

networks:
  snakenet: