version: "3"
services: 

  # NodeJS Server
  nodejs:
    build: .
    depends_on: 
      - mongo
    restart: always
    environment:
      - PORT=3000
    ports: 
      - 3000:3000
    links:
      - mongo
    networks:
      - snakenet 

  # Mongo Container
  mongo:
    image: mongo:3.4.19
    ports:
      - 27017:27017
    volumes:
      - ./.db:/data/db
    restart: always
    networks:
      - snakenet

networks:
  snakenet: