version: "3"
services: 

  # NodeJS Server
  nodejs:
    build: .
    environment:
      - PORT=3000
    ports: 
      - 3000:3000
    restart: always
    networks:
      - snakenet 

networks:
  snakenet: